repos:
  - repo: local
    hooks:
      - id: biome-check
        name: Biome Check
        entry: npm --prefix frontend run lint --silent
        language: system
        pass_filenames: false
      - id: biome-format
        name: Biome Format
        entry: npm --prefix frontend run format --silent
        language: system
        pass_filenames: false
