[project]
name = "agentflow"
version = "0.1.0"
description = "AgentFlow MVP scaffold"
requires-python = ">=3.10"
dependencies = [
  "fastapi==0.115.12",
  "uvicorn[standard]>=0.30",
  "python-dotenv>=1.0",
  "pydantic>=2.8",
  "pydantic-settings>=2.3",
  "pydantic-ai-slim[openai]>=0.0.49",
  "mcp[cli]>=0.1.0",
  "mem0>=1.0.0",
  "qdrant-client>=1.9.0",
  "redis>=5.0.7",
  "SQLAlchemy>=2.0",
  "alembic>=1.13",
  "psycopg[binary]>=3.2",
  "httpx>=0.27",
  "r2r>=0.1.0",
  "loguru>=0.7.2",
  "cryptography>=42.0.0",
  "pytest>=7.4",
  "pytest-asyncio>=0.23",
  "respx>=0.20",
  "pyjwt",
]

[tool.uv]
# If using uv, this section helps accelerate installs
